### ISSUE TITLE
please i need your help

### ISSUE THREAD

**Issue by tsoftit** [Banandana/LineSharp#10]
please this error show while I try to send message
An unhandled exception of type 'LineClient.Datatypes.TalkException' occurred in LineSharp.exe
any help please

**Comment by Banandana** [comment]
I'd need more information than that if I am going to help at all.

**Comment by hungUSer** [comment]
![image](https://cloud.githubusercontent.com/assets/15981664/11337925/caba6426-922b-11e5-9fb9-8d360c770daf.png)

Error Message 

HELP ME 
thans

Tony
