### ISSUE TITLE
problem please help me

### ISSUE THREAD

**Issue by tsoftit** [Banandana/LineSharp#11]
![screenshot_2016-01-17-21-59-15](https://cloud.githubusercontent.com/assets/11362148/12379591/3d791a24-bd66-11e5-9a6c-154cd647a303.png)
hi I have problem when I login to my account this message in screenshot occur and when I try send text message this error occur also
An unhandled exception of type 'LineSharp.Datatypes.TalkException' occurred in LineSharp.exe
please can you help me?
thanks

**Comment by tsoftit** [comment]
im update version and error in screenshot end but the error when sending message exist
"An unhandled exception of type 'LineSharp.Datatypes.TalkException' occurred in LineSharp.exe"
please help

**Comment by Banandana** [comment]
It looks as if the protocol has been changed and by attempting to use the old protocol, it fails and also notifies you of the issue via a message. This project is probably not as useful and is probably far too out of date to be of any use anymore. I'm going to update the main repo to reflect that info.
